<<<<<<< HEAD
application: snakebbss
version: 1
=======
application: snakebbs
version: 2
>>>>>>> app,yaml version2に変更
runtime: python
api_version: 1

handlers:
- url: /.*
  script: helloworld.py
  
- url: /css
  static_dir: css
